version: '2'

services:
  syslog:
    build: rsyslog

  lb:
    build: haproxy
    ports:
      - "80:80"
      - "22:22"
      - "443:443"
      - "411:411"
    links:
      - web1
      - web2
      - syslog

  web1:
    extends:
      file: gitlab-ce/gitlab.yml
      service: web
    links:
      - postgres
      - redis

  web2:
    extends:
      file: gitlab-ce/gitlab.yml
      service: web
    links:
      - postgres
      - redis
    depends_on:
      - web1

  postgres:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: bar
      POSTGRES_USER: foo
      POSTGRES_DB: gitlabhq_production
    volumes:
      - vdb:/var/lib/postgresql/data/pgdata

  nfs:
    image: itsthenetwork/nfs-server-alpine

  redis:
    image: redis

volumes:
  vdb:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  logs:
