version: '2'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        postgresql['enable'] = false
        gitlab_rails['db_host'] = "postgres"
        gitlab_rails['db_username'] = "${DB_USER}"
        gitlab_rails['db_password'] = "${DB_PASS}"
        gitlab_rails['db_database'] = "${DB_NAME}"
        redis['enable'] = false
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - 'gitlab_config:/etc/gitlab'
      - 'gitlab_logs:/var/log/gitlab'
      - 'gitlab_data:/var/opt/gitlab'
    links:
      - postgres
      - redis
    env_file: docker.env

  postgres:
    image: postgres
    env_file: docker.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - vdb:/var/lib/postgresql/data/pgdata

  redis:
    image: redis

volumes:
  vdb:
    external: true
  gitlab_config:
    external: true
  gitlab_logs:
    external: true
  gitlab_data:
    external: true
